### PR TITLE
The forecast API for OpenWeatherMap is invalid

### PR DESCRIPTION
**Pull request by parekhkb**
The forecast API listed in the instructions has the path /daily in it. This url may have changed or perhaps there is a paid subscription to OpenWeatherMap. The daily forecast is free but the URL is the following:
http://api.openweathermap.org/data/2.5/forecast?type=accurate&cnt=5&q=CITY-NAME&APPID=YOUR-API-KEY

### CODE REVIEW

**Comment by parekhkb** [comment]
@tylermcginnis Also, this new URL only gives 3 hour increments, not daily reports. So by setting cnt=5, you  actually get he next 15 hours of data, not 5 days of data.

**Comment by parekhkb** [comment]
When I call `/daily/` I get the following response`{"cod":401, "message": "Invalid API key. Please see http://openweathermap.org/faq#error401 for more info."}` 

Without the `/daily/` I am able to receive real data. I think that you might have been grandfathered in since you created your account with OpenWeatherMap some time ago I assume. Newly created accounts don't have access to that feature I think.

**Comment by parekhkb** [comment]
According to OpenWeatherMap's updated pricing, the free account no longer includes the Daily weather api.

image

**Comment by tylermcginnis** [comment]
Got it. I'll get this fixed soon. Thank you!

**Comment by parekhkb** [comment]
Opened issue #32  

I'll close this PR.

**Pull request closed without merging**
